/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eduar
 */
public class BotonVideo extends javax.swing.JFrame {

    /**
     * Creates new form BotonVideo
     */
    public BotonVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonPersonalizado5 = new BotonPersonalizado();
        botonPersonalizado6 = new BotonPersonalizado();
        botonPersonalizado7 = new BotonPersonalizado();
        botonPersonalizado8 = new BotonPersonalizado();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("NORMAL");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 90, 30));

        jLabel2.setText("SIN FONDO");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 26, 92, 30));

        jLabel3.setText("PLANO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 90, 30));

        jLabel4.setText("SIN ICONO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 157, 92, 30));

        botonPersonalizado5.setColorContorno(new java.awt.Color(255, 255, 0));
        botonPersonalizado5.setColorFondo1(new java.awt.Color(51, 255, 51));
        botonPersonalizado5.setColorFondo2(new java.awt.Color(0, 255, 255));
        botonPersonalizado5.setColorTexto(new java.awt.Color(255, 51, 51));
        botonPersonalizado5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/spider.png"))); // NOI18N
        botonPersonalizado5.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/wolverine.png"))); // NOI18N
        botonPersonalizado5.setForma(BotonPersonalizado.FormaBoton.CIRCULO);
        botonPersonalizado5.setIconoHover(new javax.swing.ImageIcon(getClass().getResource("/spider.png"))); // NOI18N
        botonPersonalizado5.setIconoNormal(new javax.swing.ImageIcon(getClass().getResource("/deadpool.png"))); // NOI18N
        getContentPane().add(botonPersonalizado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 140, 100));

        botonPersonalizado6.setText("CANCELAR");
        botonPersonalizado6.setColorSinFondo1(new java.awt.Color(204, 0, 204));
        botonPersonalizado6.setColorSinFondo2(new java.awt.Color(255, 255, 0));
        botonPersonalizado6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/spider.png"))); // NOI18N
        botonPersonalizado6.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/deadpool.png"))); // NOI18N
        botonPersonalizado6.setEstilo(BotonPersonalizado.EstiloBoton.SIN_FONDO);
        botonPersonalizado6.setForma(BotonPersonalizado.FormaBoton.OVALO);
        botonPersonalizado6.setIconoHover(new javax.swing.ImageIcon(getClass().getResource("/wolverine.png"))); // NOI18N
        botonPersonalizado6.setIconoNormal(new javax.swing.ImageIcon(getClass().getResource("/spider.png"))); // NOI18N
        getContentPane().add(botonPersonalizado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 130, 60));

        botonPersonalizado7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/deadpool.png"))); // NOI18N
        botonPersonalizado7.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/wolverine.png"))); // NOI18N
        botonPersonalizado7.setEstilo(BotonPersonalizado.EstiloBoton.PLANO);
        botonPersonalizado7.setForma(BotonPersonalizado.FormaBoton.OVALO);
        botonPersonalizado7.setIconoHover(new javax.swing.ImageIcon(getClass().getResource("/deadpool.png"))); // NOI18N
        botonPersonalizado7.setIconoNormal(new javax.swing.ImageIcon(getClass().getResource("/wolverine.png"))); // NOI18N
        getContentPane().add(botonPersonalizado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 130, 60));

        botonPersonalizado8.setText("BORRAR");
        botonPersonalizado8.setColorContorno(new java.awt.Color(51, 255, 204));
        botonPersonalizado8.setColorFondo1(new java.awt.Color(255, 255, 51));
        botonPersonalizado8.setColorFondo2(new java.awt.Color(255, 0, 255));
        botonPersonalizado8.setColorTexto(new java.awt.Color(0, 0, 0));
        botonPersonalizado8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/wolverine.png"))); // NOI18N
        botonPersonalizado8.setDisabledSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/spider.png"))); // NOI18N
        botonPersonalizado8.setEstilo(BotonPersonalizado.EstiloBoton.SIN_ICONO);
        botonPersonalizado8.setForma(BotonPersonalizado.FormaBoton.CIRCULO);
        getContentPane().add(botonPersonalizado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 130, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BotonVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BotonVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BotonVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BotonVideo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BotonVideo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private BotonPersonalizado botonPersonalizado5;
    private BotonPersonalizado botonPersonalizado6;
    private BotonPersonalizado botonPersonalizado7;
    private BotonPersonalizado botonPersonalizado8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
